name: Deploy Pages & Publish Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install --frozen-lockfile || pnpm install

    - name: Build application
      run: pnpm run build:prod

    - name: Copy index.html to 404.html (SPA routing fix)
      run: cp dist/bipal-front/browser/index.html dist/bipal-front/browser/404.html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/bipal-front/browser

    - name: Upload dist artifact (post-deploy)
      uses: actions/upload-artifact@v4
      with:
        name: dist-bipal
        path: dist/bipal-front/browser
        if-no-files-found: error

  dockerhub-publish:
    needs: build-and-deploy-pages
    uses: ./.github/workflows/dockerhub.yml
    with:
      image-name: bipal-front
      download-artifact-name: dist-bipal
      check-dist: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
